### ISSUE TITLE
Unable to import the plugin due to References to undefined settings error

### ISSUE THREAD

**Issue by therk** [gilt/sbt-codedeploy#23]
Having the following error after adding "addSbtPlugin("com.gilt" % "sbt-codedeploy" % "0.4.0")" to my plugins.sbt

[info] Loading global plugins from /Users/therk/.sbt/0.13/plugins
[info] Loading project definition from /Users/therk/workspace/EducationLink/project
References to undefined settings: 

  production:stackDescribe from production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)

  staging:stackDescribe from staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
 
	at sbt.Init$class.Uninitialized(Settings.scala:270)
	at sbt.Def$.Uninitialized(Def.scala:10)
	at sbt.Init$class.delegate(Settings.scala:191)
	at sbt.Def$.delegate(Def.scala:10)
	at sbt.Init$class.compiled(Settings.scala:138)
	at sbt.Def$.compiled(Def.scala:10)
	at sbt.Init$class.make(Settings.scala:144)
	at sbt.Def$.make(Def.scala:10)
	at sbt.Load$.apply(Load.scala:135)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:481)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:475)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings: 
[error] 
[error]   production:stackDescribe from production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error] 
[error]   staging:stackDescribe from staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]

**Comment by myyk** [comment]
Is the code available for looking at? This definitely didn't used to be the case, I'm wondering if you haven't setup everything in your Build.scala file. I've used this in production before.

**Comment by therk** [comment]
Created https://github.com/therk/CodeDeployTest to replicate the issue. Could be a conflict with another plugin/library. It is weird that I get the error on importing SBT project, not just when I try to run the "sbt codedeployPush"

**Comment by myyk** [comment]
I think you're getting a weird interaction with `sbt-cloudformation` since it also defines Production and Staging. I had them working together while at Gilt. I need to remember what to do. In the mean time, hope that helps if you want to figure it out.

**Comment by myyk** [comment]
Check out how this test project is setup, that might help: https://github.com/gilt/sbt-codedeploy/blob/db8aced22dfc7506da423406846e36f2afc5077e/src/sbt-test/stage/directory-structure/build.sbt

**Comment by MojoJojo** [comment]
Any luck with this issue? I'm also getting the same issue..would appreciate any pointers/hints on troubleshooting this..
```
client/codedeploy:codedeployBucket from client/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)

	at sbt.Init$class.Uninitialized(Settings.scala:270)
	at sbt.Def$.Uninitialized(Def.scala:10)
	at sbt.Init$class.delegate(Settings.scala:191)
	at sbt.Def$.delegate(Def.scala:10)
	at sbt.Init$class.compiled(Settings.scala:138)
	at sbt.Def$.compiled(Def.scala:10)
	at sbt.Init$class.make(Settings.scala:144)
	at sbt.Def$.make(Def.scala:10)
	at sbt.Load$.apply(Load.scala:145)
	at sbt.Load$.defaultLoad(Load.scala:36)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:492)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:492)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:484)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:59)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:54)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] References to undefined settings:
[error]
[error]   sharedJVM/production:stackDescribe from sharedJVM/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   langJVM/codedeploy:codedeployBucket from langJVM/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJS/production:stackDescribe from sharedJS/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   client/production:stackDescribe from client/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   client/codedeploy:codedeployBucket from client/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   client/codedeploy:codedeployBucket from client/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJVM/staging:stackDescribe from sharedJVM/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   langJS/codedeploy:codedeployBucket from langJS/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   langJVM/staging:stackDescribe from langJVM/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   sharedJS/codedeploy:codedeployBucket from sharedJS/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   server/codedeploy:codedeployBucket from server/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   wsclient/codedeploy:codedeployBucket from wsclient/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   server/production:stackDescribe from server/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   langJS/codedeploy:codedeployBucket from langJS/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   wsclient/production:stackDescribe from wsclient/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   langJVM/codedeploy:codedeployBucket from langJVM/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   wsclient/codedeploy:codedeployBucket from wsclient/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   client/staging:stackDescribe from client/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   contactview/codedeploy:codedeployBucket from contactview/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJVM/codedeploy:codedeployBucket from sharedJVM/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJS/staging:stackDescribe from sharedJS/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   contactview/codedeploy:codedeployBucket from contactview/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   sharedJVM/codedeploy:codedeployBucket from sharedJVM/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   langJS/codedeploy:codedeployBucket from langJS/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJS/codedeploy:codedeployBucket from sharedJS/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   sharedJVM/codedeploy:codedeployBucket from sharedJVM/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   contactview/production:stackDescribe from contactview/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   server/codedeploy:codedeployBucket from server/*:codedeployPush ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:82)
[error]
[error]   langJS/staging:stackDescribe from langJS/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   server/codedeploy:codedeployBucket from server/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   langJVM/codedeploy:codedeployBucket from langJVM/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   server/staging:stackDescribe from server/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   sharedJS/codedeploy:codedeployBucket from sharedJS/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   wsclient/staging:stackDescribe from wsclient/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   langJVM/production:stackDescribe from langJVM/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   wsclient/codedeploy:codedeployBucket from wsclient/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   contactview/codedeploy:codedeployBucket from contactview/production:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
[error]
[error]   langJS/production:stackDescribe from langJS/production:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   contactview/staging:stackDescribe from contactview/staging:codedeployCreateDeploymentGroup ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:170)
[error]
[error]   client/codedeploy:codedeployBucket from client/staging:codedeployCreateDeployment ((sbt.codedeploy.CodeDeployPlugin) CodeDeploy.scala:150)
```

**Comment by myyk** [comment]
@MojoJojo Do you have a minimal project that repros the issue or is it similar enough to this one? https://github.com/therk/CodeDeployTest

I have some time to look at it today.

**Comment by MojoJojo** [comment]
It is not similar..it is in fact a multi module SBT project. Will paste the build files shortly. Whats interesting is that the errors appear without even enabling the plugin. As soon as I add the following like to my plugins.sbt, I start getting the errors:

`addSbtPlugin("com.gilt" % "sbt-codedeploy" % "0.4.0")`

**Comment by myyk** [comment]
So I fixed the issue in the repro from @therk with this: https://github.com/therk/CodeDeployTest/pull/1

@MojoJojo I would need a repro project to really be able to help you.

**Comment by MojoJojo** [comment]
I can't put the code in a public paste but have pasted portions of it here:

```
import CommonSettings._

import com.github.tptodorov.sbt.cloudformation.CloudFormation
import com.github.tptodorov.sbt.cloudformation.Import.Keys._
import com.github.tptodorov.sbt.cloudformation.Import.Configurations._

CloudFormation.defaultSettings
stackRegion := "US_EAST_1"

name := "my-designer"

scalaVersion := "2.11.8"


lazy val server =
  DefProject("designer/server", "server")
    
    
    .enablePlugins(CodeDeployPlugin)
    

codedeployBucket in ThisBuild := "your-codedeploy-bucket-name-here"
name in CodeDeploy := "new-better-shinier-name"
name in CodeDeploy := "sbt-codedeploy-play-example"

codedeployBucket := "backoffice-codedeploy-oregon"


```


CommonSettings is defined as: 

```
import org.scalajs.sbtplugin.ScalaJSPlugin
import sbt.Keys._
import sbt._
import com.amazonaws.services.s3.model.Region


object CommonSettings {

  final val s3Region = Region.US_West_2
  final val s3CredentialsFile = file(".s3credentials")
  lazy val commonSettings =
    Seq(
      organization := "com.some.org",
      version := "0.1.0",
      homepage := Some(url("https://bitbucket.org/somerepo")),
      scalaVersion := "2.11.8",
      scalacOptions ++= Seq("-deprecation", "-unchecked", "-feature",
        "-language:postfixOps", "-language:implicitConversions",
        "-language:higherKinds", "-language:existential"))

  def DefProject(name: String, id: String = "") = {
    Project(if (id.isEmpty) name else id, file(name))
      .settings(commonSettings: _*)
  }

  def DefJSProject(name: String, id: String = "") = {
    Project(if (id.isEmpty) name else id, file(name))
      .settings(commonSettings: _*)
      .enablePlugins(ScalaJSPlugin)
  }

  def addCommandAliases(m: (String, String)*) = {
    val s = m.map(p => addCommandAlias(p._1, p._2)).reduce(_ ++ _)
    (_: Project).settings(s: _*)
  }

}
```

Project structure (simplified):

my-project
  |--designer
         |--server
 |-build.sbt
 
  Not sure if that is enough though.

**Comment by myyk** [comment]
Ok, your issue is basically the same. Your project `server` doesn't have the `sbt-cloudformation` settings. This would fix it.

```
lazy val server =
  DefProject("designer/server", "server")
    .settings(CloudFormation.defaultSettings: _*)
    .settings(stackRegion := "US_EAST_1")
    .enablePlugins(CodeDeployPlugin)
```

You could move this into your `DefProject` if that suites you better.

**Comment by MojoJojo** [comment]
Bah!!! I spent last few hours debugging that ..not sure how I missed it!!!

Thanks a million!

**Comment by myyk** [comment]
I'm going to close this as both issues were related to misuse of the `sbt-cloudformation` plugin while using this plugin.

**Comment by myyk** [comment]
Hrm... Actually I can't close it. But I recommend it be closed.

**Comment by MojoJojo** [comment]
Perhaps we can update the documentation to include this? Not sure if its already mentioned somewhere?

**Comment by gheine** [comment]
@myyk closed it for you :)

**Comment by myyk** [comment]
Thanks @gheine.

@MojoJojo and @therk I updated https://github.com/myyk/sbt-codedeploy to use `sbt-cloudformation` as an AutoPlugin now. Also updated the docs and published a new version. `0.5.0`

Docs are updated to state that the `stackRegion` is necessary.

Specifically for you @MojoJojo, your `build.sbt` would look something like this since you don't need the CloudFormation plugin on your root level:

```
disablePlugins(CloudFormation)

lazy val server =
  DefProject("designer/server", "server")
    .enablePlugins(CloudFormation, CodeDeployPlugin)
    .settings(stackRegion := "US_EAST_1")
```

**Comment by MojoJojo** [comment]
Thanks @myyk . I am hoping this would work with multi project as well? Previously, If I had a project with 5 sub projects and I wanted to use the plugin only with one, I still had to apply settings to other 4 projects for sbt to load the project. 
Gonna give this a shot right away..

**Comment by myyk** [comment]
@MojoJojo Yeah, should work with multi-project. That's what that code snippet above is for you. Just disable the `CloudFormation` plugin at the root, and enable it on the sub-projects you want. LMK if you have a problem.

**Comment by MojoJojo** [comment]
Do I need to add any resolvers for 0.5.0? When I change the version I get an `UNRESOLVED DEPENDENCIES` error.

**Comment by myyk** [comment]
@MojoJojo Yeah, follow the new instructions in this section of my fork: https://github.com/myyk/sbt-codedeploy#installation

**Comment by MojoJojo** [comment]
I added the new resolver..but now it gives me error below:

```
resolvers += Resolver.url("myyk-bintray-sbt-plugins", url("https://dl.bintray.com/myyk/sbt-plugins/"))(Resolver.ivyStylePatterns)
```

Error:

```
[warn] ==== myyk-bintray-sbt-plugins: tried
[warn]   https://dl.bintray.com/myyk/sbt-plugins/com.gilt/sbt-codedeploy/scala_2.10/sbt_0.13/0.5.0/ivys/ivy.xml
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.gilt#sbt-codedeploy;0.5.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
```

**Comment by MojoJojo** [comment]
My bad. I didn't read the new instructions properly..

**Comment by MojoJojo** [comment]
Okay, I read the instructions now and added the following lines in my plugins.sbt:

```
resolvers += Resolver.url("myyk-bintray-sbt-plugins", url("https://dl.bintray.com/myyk/sbt-plugins/"))(Resolver.ivyStylePatterns)

addSbtPlugin("com.github.myyk" % "sbt-cloudformation" % "0.7.1")
addSbtPlugin("com.github.myyk" % "sbt-codedeploy" % "0.5.0")
```

I get the error below:

```
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.myyk#sbt-cloudformation;0.7.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
```

**Comment by myyk** [comment]
Sorry, I had a line wrong in there. I'll update, should be:

`addSbtPlugin("com.github.tptodorov" % "sbt-cloudformation" % "0.7.1")`

**Comment by MojoJojo** [comment]
Okay, Now I'm getting the error below. Think its conflicting with the s3 resolver plugin...

```
[warn] two warnings found
warning: Class com.amazonaws.transform.JsonErrorUnmarshallerV2 not found - continuing with a stub.

java.lang.NoSuchMethodError: com.amazonaws.http.AmazonHttpClient.disableStrictHostnameVerification()V
       	at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:444)
       	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:391)
       	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:368)
       	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:350)
       	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:334)
       	at ohnosequences.ivy.S3Repository.<init>(S3Repository.java:85)
       	at ohnosequences.ivy.S3Resolver.<init>(S3Resolver.java:48)
       	at ohnosequences.sbt.SbtS3Resolver$autoImport$S3Resolver.<init>(SBTS3Resolver.scala:14)
       	at ohnosequences.sbt.SbtS3Resolver$$anonfun$projectSettings$7$$anonfun$apply$1.apply(SBTS3Resolver.scala:101)
       	at ohnosequences.sbt.SbtS3Resolver$$anonfun$projectSettings$7$$anonfun$apply$1.apply(SBTS3Resolver.scala:101)
       	at ServerSettings$$anonfun$24.apply(ServerSettings.scala:125)
       	at ServerSettings$$anonfun$24.apply(ServerSettings.scala:119)
       	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
       	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
       	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
       	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
       	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
       	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
[error] java.lang.NoSuchMethodError: com.amazonaws.http.AmazonHttpClient.disableStrictHostnameVerification()V
[error] Use 'last' for the full log.
```

**Comment by myyk** [comment]
Let's move this discussion to https://github.com/myyk/sbt-codedeploy/issues/2 since this is an error with the `myyk/sbt-codedeploy` not `gilt/sbt-codedeploy`
